### PR TITLE
fix(runtime-vapor): fix v-show value

### LINKED ISSUE #72: [bug] Incorrect parameter in v-show directive
## Describe the Issue
In the v-show directive, I noticed an issue regarding the incorrect parameter being used.

## Steps to Reproduce

1. Set the visible default value to false in the playground.
2. Use the v-show directive with a value of true.

https://github.com/vuejs/core-vapor/blob/597eae423b0d69fba47b0ac6a1e9692fb4a95f71/packages/runtime-vapor/src/directives/vShow.ts#L5-L9

It appears that the `source` value returned in the beforeMount function is a function **(_ctx.visible)**. Therefore, it is suggested to use the value parameter, similar to how it is used in the updated function.

### PR DESCRIPTION
**Pull request by kaine0923**
closes #72

### CODE REVIEW

File: packages/runtime-vapor/src/directives/vShow.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import type { ObjectDirective } from '../directive'
 const vShowMap = new WeakMap<HTMLElement, string>()
 
 export const vShow: ObjectDirective<HTMLElement> = {
-  beforeMount(node, { source: value }) {
+  beforeMount(node, { value }) {
```
Comment (baiwusanyu-c) [inline packages/runtime-vapor/src/directives/vShow.ts:6]: I think you should submit an issue to describe the problem first. This will help others locate the problem more accurately. What do you think?🧐
And when necessary, it is best to add unit tests

**Review by sxzz — APPROVED** [review]
